#!/bin/bash

# Script to update version across all files
# Usage: ./scripts/update_version.sh 1.2.3

set -e

if [ $# -ne 1 ]; then
    echo "Usage: $0 <version>"
    echo "Example: $0 1.2.3"
    exit 1
fi

NEW_VERSION=$1

# Validate version format: x.x.x
if [[ ! "$NEW_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "❌ Error: Version must be in x.y.z format (e.g., 1.2.3)"
    exit 1
fi

# Parse version components
IFS='.' read -r MAJOR MINOR PATCH <<< "$NEW_VERSION"

echo "Updating version to $NEW_VERSION..."

# Write to VERSION file
echo "$NEW_VERSION" > VERSION

# Update version.h
cat > src/include/version.h << EOF
// generated by scripts/bump.sh - do not edit manually

#ifndef version_h
#define version_h

#define APPLICATION_NAME "Lavandula"

#define VERSION_MAJOR    $MAJOR
#define VERSION_MINOR    $MINOR
#define VERSION_PATCH    $PATCH

#endif
EOF

echo "Version updated to $NEW_VERSION"
echo "Don't forget to:"
echo "   1. Update changelog.md"
echo "   2. Commit changes: git add . && git commit -m 'Bump version to $NEW_VERSION'"
